# This is a basic workflow to help you get started with Actions
name: 06 Expressions

# https://docs.github.com/en/actions/learn-github-actions/expressions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  formatting: ${{ format('{{Hello {0} {1} {2}!}}', 'Mona', 'the', 'Octocat') }}
  endsWith: ${{ endsWith('Hello world', 'ld') }}
  containsString: ${{ contains('Hello world', 'llo') }}
  containsArray: ${{ contains(fromJson('["Chris","Michael"]'), 'chris') }}
  presentersString: ${{ join(fromJson('["Chris","Michael"]'), ', ') }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print formatting
        run: echo "$formatting"
      - name: Print endsWith
        run: echo "$endsWith"
      - name: Print containsString
        run: echo "$containsString"
      - name: Print containsArray
        run: echo "$containsArray"
      - name: Print Presenters
        run: echo "$presentersString"
